### ISSUE TITLE
Get current context when debugging

### ISSUE THREAD

**Issue by rodfersou** [auiWorks/amCoffee#22]
When I use a break point I would like to get current context to debug, so I can inspect local variables instead of just global ones.
![amcoffee](https://cloud.githubusercontent.com/assets/131209/5010660/8e4cf08c-6a5c-11e4-9555-99891ddc5934.png)

**Comment by darrrk** [comment]
:+1:

**Comment by DiegeticShadow** [comment]
+1 Also see my comment to #7, possibly related?

**Comment by steel** [comment]
:+1:

**Comment by rodfersou** [comment]
@DiegeticShadow yes, I think this is related... and if there is no way to get the right context with breakpoints (as explained in #7 ), I think we should close this issue too
