### ISSUE TITLE
CofffeeScript can't access the JS Objects in break points

### ISSUE THREAD

**Issue by tiye** [auiWorks/amCoffee#7]
As JS stopped at a break point, code in amCoffee returns `undefined` to a local variable.

**Comment by DiegeticShadow** [comment]
I just checked https://developer.chrome.com/extensions/devtools.inspectedWindow.html#method-eval today, and it has a note that **as of Chrome 38** there’s an option called `useContentScriptContext` that allows one to “Evaluate the expression in the context of the content script of the calling extension”. I don’t know if this is no improvement over what the API looked like in 2013, but I thought I’d bring it to everyone’s attention. Would the current API allow us to run CoffeeScript in the current context when paused at a breakpoint?

**Comment by aioutecism** [comment]
@DiegeticShadow 
Sadly, `useContentScriptContext` is used to communicate with this extension's content script. It still cannot access variables in the local context.
